---
#
- name: install camunda
  unarchive:
    src: "{{ camunda_url }}"
    dest: "{{ camunda_base }}"
    owner: "{{ camunda_user }}"
    copy: no
    creates: "{{ camunda_home }}/bin/camunda"
  become: yes
