---
#
- name: install camunda
  unarchive:
    src: "{{ camunda_url }}"
    dest: "{{ camunda_home }}"
    owner: "{{ camunda_user }}"
    copy: no
    creates: "{{ camunda_home }}/start_camunda.sh"
  become: yes
